#!/usr/bin/env bash

set -euo pipefail

# Use static ref if provided, otherwise default to branch name placeholder
head="${1:-"{branch}"}"
api_url="/repos/{owner}/{repo}/commits/${head}/status"
output_template='
{{- range .statuses -}}
	{{ " " }}
    {{- if (eq .state "success") -}}
        {{- autocolor "green" "▪" -}}
    {{- else -}}
        {{- if (eq .state "pending") -}}
            {{- autocolor "yellow" "▪" -}}
        {{- else -}}
            {{- autocolor "red" "▪" -}}
        {{- end -}}
    {{- end -}}
    {{ " " }}
    {{- if .target_url -}}
        {{- hyperlink .target_url (autocolor "default+b" .context) -}}
    {{- else -}}
        {{- autocolor "default+b" .context -}}
    {{- end -}}
    {{ " " }}
    {{- autocolor "250:default" .description -}}
    {{- "\n"}}
{{- else -}}
	 {{ "No statuses" }}
	 {{- "\n"}}
{{- end -}}'

# Do not pipe gh output to a pager
unset PAGER

exec gh api --template="$output_template" "$api_url"
