#!/usr/bin/env bash

set -euo pipefail

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# Do not pipe gh output to a pager
unset PAGER

print_recent_releases() {
	gh release list --limit=10
}

get_releases() {
	template='
{{- range . -}}
  {{ " - " }}{{- .tag_name -}} {{- "\n"}}
{{- end -}}
'
	gh api '/repos/{owner}/{repo}/releases' --template="$template"
}

if [ -z "$(print_recent_releases)" ]; then
	echo 'This repository has no releases'
	exit
fi

if ! [ "$(gh api '/repos/{owner}/{repo}/commits/{branch}/status' --jq='.state')" = 'pending' ]; then
	echo 'Commit status is not "pending", so here are the ten most recent releases:'
	print_recent_releases
	exit
fi

prev_releases="$(get_releases)"
"$_dir"/watch-commit-status
# `diff` exits `1` when differences are found
set +e
# Diff, only displaying changed groups, and hiding any control characters
diff="$(diff \
	--ignore-all-space \
	--changed-group-format='%<%>' \
	<(echo "$prev_releases") <(get_releases)
)"
set -e

if [ -z "$diff" ]; then
	echo 'There are no new releases since running this command, so here are the most recent releases:'
	print_recent_releases
	exit
fi

echo "$diff"
